# Generated by Django 3.1.3 on 2021-02-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='in_stock_unit',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
