# Generated by Django 3.1.3 on 2021-02-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0002_commodity_in_stock_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity',
            name='sales_unit',
        ),
        migrations.AlterField(
            model_name='commodity',
            name='in_stock_unit',
            field=models.CharField(choices=[('KG', 'kg'), ('MG', 'mg'), ('PIECES', 'pieces')], max_length=10),
        ),
    ]
