# Generated by Django 3.1.3 on 2021-02-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0003_auto_20210215_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='price',
            field=models.PositiveIntegerField(verbose_name='For 100 Mg of Product'),
        ),
    ]
