# Generated by Django 3.1.3 on 2021-02-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0004_auto_20210215_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='price',
            field=models.PositiveIntegerField(help_text='For 100 Mg of Product'),
        ),
    ]
