# Generated by Django 3.1.6 on 2021-02-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0005_auto_20210215_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='image',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
    ]
