# Generated by Django 3.1.6 on 2021-02-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0007_auto_20210219_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='image',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
