# Generated by Django 3.1.6 on 2021-02-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0008_auto_20210219_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='minimum_unit',
            field=models.CharField(default='per 100mg', max_length=20),
            preserve_default=False,
        ),
    ]
